
# 액션에 사용되는 이름

name: Test

# 워크플로우가 발생될 때의 이벤트
on:
  # 작성된 브런치가 push 혹은 pull_request될 때 발생
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 수동으로 발생
  workflow_dispatch:

# 워크플로우에서 처리할 때의 잡
jobs:
  # 잡의 이름을 설정
  build:
    # 잡을 시작할 때 움직이는 러너의 구성
    runs-on: ubuntu-latest

    # 러너 이벤트
    steps:
      # 러너 쉘에 작동시킬 시나리오(테스트 혹은 배포)
      - name: Start Python test by pytest
        run: |
          python -m pip install --upgrade pip
					pip install pytest
					pytest test.py
